version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carflex_db
      MYSQL_USER: lavan
      MYSQL_PASSWORD: lavan123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  springboot:
    build:
      context: ./SpringBoot
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flex
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lavan@167
    depends_on:
      - mysql
    networks:
      - app-network

  angular:
    build:
      context: ./Angular
      dockerfile: Dockerfile
    container_name: angular-container
    ports:
      - "4200:80"
    depends_on:
      - springboot
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
