services:
  # Spring Boot Backend Service (corrected type and added critical Java config)
  - type: web  # ✅ "web" not "pserv" - required for Java apps
    name: springboot-app
    rootDir: SpringBoot
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: RENDER_INFER_RUNTIME  # ✅ Forces Java detection
        value: java
      - key: SERVER_PORT  # ✅ Double-binding for Spring Boot
        value: $PORT
      - key: NODE_ENV  # ✅ Required for Angular build via Maven
        value: production
    plan: free
    autoDeploy: yes
    branch: main

  # Angular Frontend Service (optimized static config)
  - type: static  # ✅ "static" not "web" for SPAs
    name: angular-app
    rootDir: Angular
    buildCommand: npm install && npm run build -- --configuration=production
    publishPath: dist/Flex  # ✅ "publishPath" instead of "staticPublishPath"
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL  # ✅ Add your API endpoint if using Vite
        value: https://springboot-app.onrender.com
    plan: free
    autoDeploy: yes
    branch: main