services:
  # Angular Frontend Service (Production)
  - type: web
    name: angular-app
    runtime: node
    rootDir: Angular
    buildCommand: |
      npm install
      npm run build -- --configuration=production
      npm install -g serve  # Ensure serve is available globally
    startCommand: serve -s dist/Flex -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL  # Example environment variable
        value: https://your-backend-service.onrender.com
    plan: free
    autoDeploy: yes
    branch: main
    healthCheckPath: /  # Recommended for web services
    nodeVersion: 20  # Matches your Angular 18 requirements

  # Optional: Spring Boot Backend Service (if needed)
  - type: web
    name: springboot-app
    env: java  # Correct Java declaration for Render
    rootDir: SpringBoot
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: $PORT
      - key: RENDER_FORCE_JAVA
        value: "true"
    plan: free
    autoDeploy: yes
    branch: main
    javaVersion: 21