services:
  - type: pserv  # ✅ Spring Boot backend
    name: springboot-app
    rootDir: SpringBoot
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: RENDER_BUILD_JAVA_VERSION
        value: 21
    branch: main
    autoDeploy: yes
    plan: free

  - type: web  # ✅ Angular frontend
    name: angular-app
    runtime: static
    rootDir: Angular
    buildCommand: npm install && npm run build -- --configuration=production
    staticPublishPath: dist/Flex  # 👈 make sure this matches your Angular build output
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_BUILD_NODE_VERSION
        value: 20
    branch: main
    autoDeploy: yes
    plan: free
