services:
  # Spring Boot Service (Blueprint-Compatible)
  - type: web
    name: springboot-app
    # NO runtime/env declaration - this is intentional
    rootDir: SpringBoot
    buildCommand: |
      chmod +x ./mvnw
      ./mvnw clean install -DskipTests
      # Create marker file to force Java detection
      echo "java" > .render-runtime
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: RENDER_INFER_RUNTIME
        value: java
      - key: RENDER_FORCE_JAVA
        value: "true"
      - key: SERVER_PORT
        value: $PORT
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx512m -Dfile.encoding=UTF-8"
      - key: MAVEN_OPTS
        value: "-Djava.version=21"
    plan: free
    autoDeploy: yes
    branch: main

  # Angular Service (unchanged)
  - type: web
    name: angular-app
    runtime: node
    rootDir: Angular
    buildCommand: |
      npm install
      npm run build -- --configuration=production
    startCommand: npx serve -s dist/Flex -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://springboot-app.onrender.com
      - key: NODE_VERSION
        value: "20"
    plan: free
    autoDeploy: yes
    branch: main