services:
  - type: web
    name: springboot-app
    runtime: java
    rootDir: SpringBoot  # 👈 Points Render to your backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    branch: main
    autoDeploy: yes
    plan: free
    javaVersion: 21
