services:
  - type: web
    name: springboot-app
    runtime: java
    rootDir: SpringBoot  # Folder containing pom.xml
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    branch: main
    autoDeploy: yes
    plan: free
    javaVersion: 21

  - type: web
    name: angular-app
    runtime: node
    rootDir: Angular  # Folder containing angular.json
    buildCommand: npm install && npm run build -- --configuration=production
    staticPublishPath: dist/Flex  # 👈 Replace this
    envVars:
      - key: NODE_ENV
        value: production
    branch: main
    autoDeploy: yes
    plan: free
    nodeVersion: 20
