services:
  # Spring Boot Backend Service
  - type: web
    name: springboot-app
    rootDir: SpringBoot
    buildCommand: |
      chmod +x ./mvnw
      ./mvnw clean install
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: $PORT
      - key: RENDER_FORCE_JAVA
        value: "true"  # Optional, but helps Render recognize Java
    plan: free
    autoDeploy: yes
    branch: main

  # Angular Frontend Service
  - type: web
    name: angular-app
    runtime: node
    rootDir: Angular
    buildCommand: |
      npm install
      npm run build -- --configuration=production
    startCommand: npx serve -s dist/Flex -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://springboot-app.onrender.com
      - key: NODE_VERSION
        value: "20"
    plan: free
    autoDeploy: yes
    branch: main
