services:
  # Spring Boot Backend Service (Web Service)
  - type: web
    name: springboot-app
    env: java  # Render's legacy Java declaration
    rootDir: SpringBoot
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: $PORT
      - key: RENDER_FORCE_JAVA
        value: "true"  # Nuclear option for Java
    plan: free
    autoDeploy: yes
    branch: main

  # Angular Frontend Service (Static Site)
  - type: static  # Proper static site declaration
    name: angular-app
    rootDir: Angular
    buildCommand: npm install && npm run build -- --configuration=production
    publishPath: dist/Flex  # Correct key for static
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://springboot-app.onrender.com
    plan: free
    autoDeploy: yes
    branch: main