services:
  # Spring Boot Backend Service (No buildpack needed)
  - type: web
    name: springboot-app
    rootDir: SpringBoot
    buildCommand: |
      chmod +x ./mvnw
      ./mvnw clean install -DskipTests
    startCommand: java -jar target/SpringBoot-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: RENDER_INFER_RUNTIME
        value: java
      - key: RENDER_FORCE_JAVA
        value: "true"
      - key: SERVER_PORT
        value: $PORT
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: "21"
    plan: free
    autoDeploy: yes
    branch: main

  # Angular Frontend Service
  - type: web
    name: angular-app
    runtime: node
    rootDir: Angular
    buildCommand: |
      npm install
      npm run build -- --configuration=production
    startCommand: npx serve -s dist/Flex -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://springboot-app.onrender.com
      - key: PORT
        value: "3000"
    nodeVersion: 20
    plan: free
    autoDeploy: yes
    branch: main